# -*- coding: utf-8 -*-
"""accenture project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDm4LzvfqPjF0i6nPo3uHkkKhCjK6aKU
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

reactiontypes = pd.read_csv('ReactionTypes.csv')
reactions = pd.read_csv('Reactions.csv')
content = pd.read_csv('Content.csv')

reactiontypes.drop('Unnamed: 0',axis = 1, inplace = True)

reactions.drop('Unnamed: 0',axis = 1, inplace = True)

reactions

content.drop('Unnamed: 0',axis = 1, inplace = True)

content

reactions

reactiontypes

df = content.merge(reactions,how='left', on = 'User ID')

df= df.rename(columns={'Type_x':'Content_Type', 'Type_y':'Reaction_Type'})

"""change column name"""

r1= reactiontypes.rename(columns = {'Type':'Reaction_Type'})

df = df.merge(r1, how = 'left', on = 'Reaction_Type')

df

df.head()

df.info()



"""total 10 columns 
44877 entries
null value: URL, recommend delete it 
"""

df.isnull().sum()

df.isnull().sum()/df.shape [0]

df.drop('URL', axis = 1, inplace = True)

df.head()

df.info()

df.duplicated().sum()

df['Category'].unique()

df['Category'] = df['Category'].replace('"', '', regex = True)
df['Category'] = df['Category'].str.lower()

df['Category'].unique()

df

df1 = df.groupby('Category').agg({"Reaction_Type" : "count"}).reset_index().sort_values(by='Reaction_Type', ascending=False).head(5)

df2 = df.groupby('Category').agg({"Score" : "sum"}).reset_index().sort_values(by='Score', ascending=False).head()

df1.to_csv('data1.csv', index = False)
files.download("data1.csv")

df2.to_csv('data2.csv', index = False)
files.download("data2.csv")

df.to_csv('data.csv', index = False)
# export csv file without index and header

files.download("data.csv") 
 

# download csv file to local drive



